// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dice.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{0}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{1}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{2}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*UserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{3}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

type ActivityResponse struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Actor                string   `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	RepoName             string   `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Summaryline          string   `protobuf:"bytes,5,opt,name=summaryline,proto3" json:"summaryline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityResponse) Reset()         { *m = ActivityResponse{} }
func (m *ActivityResponse) String() string { return proto.CompactTextString(m) }
func (*ActivityResponse) ProtoMessage()    {}
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{4}
}
func (m *ActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityResponse.Unmarshal(m, b)
}
func (m *ActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityResponse.Marshal(b, m, deterministic)
}
func (dst *ActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityResponse.Merge(dst, src)
}
func (m *ActivityResponse) XXX_Size() int {
	return xxx_messageInfo_ActivityResponse.Size(m)
}
func (m *ActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityResponse proto.InternalMessageInfo

func (m *ActivityResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ActivityResponse) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *ActivityResponse) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *ActivityResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ActivityResponse) GetSummaryline() string {
	if m != nil {
		return m.Summaryline
	}
	return ""
}

type UserActivityResponse struct {
	Activity             []*ActivityResponse `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserActivityResponse) Reset()         { *m = UserActivityResponse{} }
func (m *UserActivityResponse) String() string { return proto.CompactTextString(m) }
func (*UserActivityResponse) ProtoMessage()    {}
func (*UserActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{5}
}
func (m *UserActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivityResponse.Unmarshal(m, b)
}
func (m *UserActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivityResponse.Marshal(b, m, deterministic)
}
func (dst *UserActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivityResponse.Merge(dst, src)
}
func (m *UserActivityResponse) XXX_Size() int {
	return xxx_messageInfo_UserActivityResponse.Size(m)
}
func (m *UserActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivityResponse proto.InternalMessageInfo

func (m *UserActivityResponse) GetActivity() []*ActivityResponse {
	if m != nil {
		return m.Activity
	}
	return nil
}

type RepositoryResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryResponse) Reset()         { *m = RepositoryResponse{} }
func (m *RepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*RepositoryResponse) ProtoMessage()    {}
func (*RepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{6}
}
func (m *RepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryResponse.Unmarshal(m, b)
}
func (m *RepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryResponse.Marshal(b, m, deterministic)
}
func (dst *RepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryResponse.Merge(dst, src)
}
func (m *RepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_RepositoryResponse.Size(m)
}
func (m *RepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryResponse proto.InternalMessageInfo

func (m *RepositoryResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserRepositoriesResponse struct {
	Repository           []*RepositoryResponse `protobuf:"bytes,1,rep,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserRepositoriesResponse) Reset()         { *m = UserRepositoriesResponse{} }
func (m *UserRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*UserRepositoriesResponse) ProtoMessage()    {}
func (*UserRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_6b399ee3c202853a, []int{7}
}
func (m *UserRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRepositoriesResponse.Unmarshal(m, b)
}
func (m *UserRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRepositoriesResponse.Marshal(b, m, deterministic)
}
func (dst *UserRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRepositoriesResponse.Merge(dst, src)
}
func (m *UserRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_UserRepositoriesResponse.Size(m)
}
func (m *UserRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRepositoriesResponse proto.InternalMessageInfo

func (m *UserRepositoriesResponse) GetRepository() []*RepositoryResponse {
	if m != nil {
		return m.Repository
	}
	return nil
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "protobuf.ListUsersRequest")
	proto.RegisterType((*UserRequest)(nil), "protobuf.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "protobuf.UserResponse")
	proto.RegisterType((*ListUsersResponse)(nil), "protobuf.ListUsersResponse")
	proto.RegisterType((*ActivityResponse)(nil), "protobuf.ActivityResponse")
	proto.RegisterType((*UserActivityResponse)(nil), "protobuf.UserActivityResponse")
	proto.RegisterType((*RepositoryResponse)(nil), "protobuf.RepositoryResponse")
	proto.RegisterType((*UserRepositoriesResponse)(nil), "protobuf.UserRepositoriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiceClient is the client API for Dice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UserActivity(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserActivityResponse, error)
	UserRepositories(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserRepositoriesResponse, error)
}

type diceClient struct {
	cc *grpc.ClientConn
}

func NewDiceClient(cc *grpc.ClientConn) DiceClient {
	return &diceClient{cc}
}

func (c *diceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceClient) UserActivity(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserActivityResponse, error) {
	out := new(UserActivityResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/UserActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceClient) UserRepositories(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserRepositoriesResponse, error) {
	out := new(UserRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/UserRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiceServer is the server API for Dice service.
type DiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UserActivity(context.Context, *UserRequest) (*UserActivityResponse, error)
	UserRepositories(context.Context, *UserRequest) (*UserRepositoriesResponse, error)
}

func RegisterDiceServer(s *grpc.Server, srv DiceServer) {
	s.RegisterService(&_Dice_serviceDesc, srv)
}

func _Dice_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dice_UserActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).UserActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/UserActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).UserActivity(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dice_UserRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).UserRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/UserRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).UserRepositories(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Dice",
	HandlerType: (*DiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _Dice_ListUsers_Handler,
		},
		{
			MethodName: "UserActivity",
			Handler:    _Dice_UserActivity_Handler,
		},
		{
			MethodName: "UserRepositories",
			Handler:    _Dice_UserRepositories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dice.proto",
}

func init() { proto.RegisterFile("dice.proto", fileDescriptor_dice_6b399ee3c202853a) }

var fileDescriptor_dice_6b399ee3c202853a = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x8e, 0xd3, 0x30,
	0x18, 0x54, 0xbb, 0xed, 0xaa, 0xfd, 0xb2, 0x42, 0xe5, 0xd3, 0x02, 0x21, 0x5b, 0xa0, 0xf8, 0x54,
	0x24, 0xd4, 0x48, 0x8b, 0xc4, 0x89, 0x4b, 0x25, 0x8e, 0xb0, 0x87, 0x08, 0x24, 0x6e, 0x2b, 0x6f,
	0xfa, 0x51, 0x59, 0x6a, 0xe3, 0x60, 0x3b, 0x48, 0x11, 0xe2, 0xc2, 0x2b, 0x70, 0xe3, 0x45, 0x78,
	0x10, 0x5e, 0x81, 0x07, 0x41, 0xb1, 0x9d, 0x1f, 0x12, 0xd8, 0x53, 0xe2, 0xf1, 0x68, 0x66, 0xbe,
	0xf9, 0x0c, 0xb0, 0x13, 0x29, 0x6d, 0x72, 0x25, 0x8d, 0xc4, 0x99, 0xfd, 0xdc, 0x14, 0x1f, 0xa3,
	0xe5, 0x5e, 0xca, 0xfd, 0x81, 0x62, 0x9e, 0x8b, 0x98, 0x67, 0x99, 0x34, 0xdc, 0x08, 0x99, 0x69,
	0xc7, 0x63, 0x08, 0x8b, 0x37, 0x42, 0x9b, 0xf7, 0x9a, 0x94, 0x4e, 0xe8, 0x53, 0x41, 0xda, 0xb0,
	0x67, 0x10, 0x54, 0x67, 0x7f, 0xc4, 0x08, 0x66, 0x85, 0x26, 0x95, 0xf1, 0x23, 0x85, 0xa3, 0xd5,
	0x68, 0x3d, 0x4f, 0x9a, 0x33, 0x7b, 0x0b, 0x67, 0x8e, 0xaa, 0x73, 0x99, 0x69, 0xba, 0x8d, 0x8b,
	0x4f, 0xe1, 0x6c, 0x27, 0x74, 0x7e, 0xe0, 0xe5, 0xb5, 0xbd, 0x1f, 0xdb, 0xfb, 0xc0, 0x63, 0x57,
	0x95, 0xdc, 0x16, 0xee, 0x76, 0xd2, 0x78, 0xcd, 0xe7, 0x30, 0xad, 0x34, 0x74, 0x38, 0x5a, 0x9d,
	0xac, 0x83, 0xcb, 0xfb, 0x9b, 0x7a, 0xb4, 0x4d, 0xd7, 0x3a, 0x71, 0x24, 0xf6, 0x63, 0x04, 0x8b,
	0x6d, 0x6a, 0xc4, 0x67, 0x61, 0xca, 0x46, 0xe2, 0x11, 0x40, 0xaa, 0x88, 0x1b, 0xda, 0x5d, 0x73,
	0xe3, 0x83, 0xcd, 0x3d, 0xb2, 0x35, 0x78, 0x0e, 0x53, 0x9e, 0x1a, 0xa9, 0x7c, 0x24, 0x77, 0xc0,
	0x0b, 0x98, 0x2b, 0xca, 0xa5, 0x0b, 0x7b, 0xe2, 0x86, 0xa9, 0x80, 0x2a, 0x29, 0x22, 0x4c, 0x4c,
	0x99, 0x53, 0x38, 0xb1, 0xb8, 0xfd, 0xc7, 0x15, 0x04, 0xba, 0x38, 0x1e, 0xb9, 0x2a, 0x0f, 0x22,
	0xa3, 0x70, 0xea, 0xe6, 0xeb, 0x40, 0xec, 0x0a, 0xce, 0xab, 0xcc, 0x83, 0x7c, 0x2f, 0x61, 0xc6,
	0x3d, 0xe6, 0xa7, 0x8c, 0xda, 0x29, 0xfb, 0xec, 0xa4, 0xe1, 0xb2, 0x35, 0x60, 0x42, 0xb9, 0xd4,
	0xc2, 0x48, 0xd5, 0xaa, 0x21, 0x4c, 0x3a, 0x0b, 0xb0, 0xff, 0xec, 0x03, 0x84, 0xae, 0x2d, 0xcf,
	0x16, 0xd4, 0x16, 0xfc, 0x0a, 0x40, 0x35, 0x2a, 0xde, 0x7f, 0xd9, 0xfa, 0x0f, 0x1d, 0x92, 0x0e,
	0xff, 0xf2, 0xe7, 0x18, 0x26, 0xaf, 0x45, 0x4a, 0xf8, 0x0e, 0xe6, 0xcd, 0xf2, 0xb0, 0x93, 0xbf,
	0xff, 0xbe, 0xa2, 0x8b, 0x7f, 0xde, 0x39, 0x69, 0x76, 0xe7, 0xdb, 0xaf, 0xdf, 0xdf, 0xc7, 0x33,
	0x3c, 0x8d, 0xed, 0x3e, 0x51, 0xb8, 0x17, 0x56, 0x97, 0x80, 0xf7, 0xfa, 0xeb, 0x77, 0x9a, 0x8f,
	0xff, 0x86, 0xfb, 0x9d, 0x31, 0x66, 0x65, 0x97, 0x18, 0x39, 0xd9, 0xf8, 0x4b, 0xfd, 0x2c, 0xbf,
	0xc6, 0x75, 0x9b, 0x98, 0xc1, 0xa2, 0xdf, 0xd1, 0xff, 0xec, 0x58, 0x1f, 0x1e, 0xd6, 0xca, 0x9e,
	0x58, 0xcb, 0x87, 0xf8, 0x60, 0x68, 0x69, 0xeb, 0xbb, 0x39, 0xb5, 0x1a, 0x2f, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xcd, 0xd7, 0x12, 0x60, 0xb8, 0x03, 0x00, 0x00,
}
