// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dice.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{0}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{1}
}
func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (dst *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(dst, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{2}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type ListUsersResponse struct {
	Users                []*UserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{3}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*UserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

type ActivityResponse struct {
	CreatedAt            string   `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Actor                string   `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	RepoName             string   `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Summaryline          string   `protobuf:"bytes,5,opt,name=summaryline,proto3" json:"summaryline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivityResponse) Reset()         { *m = ActivityResponse{} }
func (m *ActivityResponse) String() string { return proto.CompactTextString(m) }
func (*ActivityResponse) ProtoMessage()    {}
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{4}
}
func (m *ActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivityResponse.Unmarshal(m, b)
}
func (m *ActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivityResponse.Marshal(b, m, deterministic)
}
func (dst *ActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivityResponse.Merge(dst, src)
}
func (m *ActivityResponse) XXX_Size() int {
	return xxx_messageInfo_ActivityResponse.Size(m)
}
func (m *ActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivityResponse proto.InternalMessageInfo

func (m *ActivityResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ActivityResponse) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *ActivityResponse) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *ActivityResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ActivityResponse) GetSummaryline() string {
	if m != nil {
		return m.Summaryline
	}
	return ""
}

type UserActivityResponse struct {
	Activity             []*ActivityResponse `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UserActivityResponse) Reset()         { *m = UserActivityResponse{} }
func (m *UserActivityResponse) String() string { return proto.CompactTextString(m) }
func (*UserActivityResponse) ProtoMessage()    {}
func (*UserActivityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{5}
}
func (m *UserActivityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserActivityResponse.Unmarshal(m, b)
}
func (m *UserActivityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserActivityResponse.Marshal(b, m, deterministic)
}
func (dst *UserActivityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserActivityResponse.Merge(dst, src)
}
func (m *UserActivityResponse) XXX_Size() int {
	return xxx_messageInfo_UserActivityResponse.Size(m)
}
func (m *UserActivityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserActivityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserActivityResponse proto.InternalMessageInfo

func (m *UserActivityResponse) GetActivity() []*ActivityResponse {
	if m != nil {
		return m.Activity
	}
	return nil
}

type RepositoryResponse struct {
	Name                 string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TeamMembers          []*UserResponse `protobuf:"bytes,2,rep,name=team_members,json=teamMembers,proto3" json:"team_members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RepositoryResponse) Reset()         { *m = RepositoryResponse{} }
func (m *RepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*RepositoryResponse) ProtoMessage()    {}
func (*RepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{6}
}
func (m *RepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryResponse.Unmarshal(m, b)
}
func (m *RepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryResponse.Marshal(b, m, deterministic)
}
func (dst *RepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryResponse.Merge(dst, src)
}
func (m *RepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_RepositoryResponse.Size(m)
}
func (m *RepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryResponse proto.InternalMessageInfo

func (m *RepositoryResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RepositoryResponse) GetTeamMembers() []*UserResponse {
	if m != nil {
		return m.TeamMembers
	}
	return nil
}

type UserRepositoriesResponse struct {
	Repository           []*RepositoryResponse `protobuf:"bytes,1,rep,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserRepositoriesResponse) Reset()         { *m = UserRepositoriesResponse{} }
func (m *UserRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*UserRepositoriesResponse) ProtoMessage()    {}
func (*UserRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{7}
}
func (m *UserRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRepositoriesResponse.Unmarshal(m, b)
}
func (m *UserRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRepositoriesResponse.Marshal(b, m, deterministic)
}
func (dst *UserRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRepositoriesResponse.Merge(dst, src)
}
func (m *UserRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_UserRepositoriesResponse.Size(m)
}
func (m *UserRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRepositoriesResponse proto.InternalMessageInfo

func (m *UserRepositoriesResponse) GetRepository() []*RepositoryResponse {
	if m != nil {
		return m.Repository
	}
	return nil
}

type RepositoryResponse2 struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NodeID               string   `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	DefaultBranch        string   `protobuf:"bytes,7,opt,name=DefaultBranch,proto3" json:"DefaultBranch,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	PushedAt             string   `protobuf:"bytes,9,opt,name=PushedAt,proto3" json:"PushedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	Fork                 bool     `protobuf:"varint,11,opt,name=Fork,proto3" json:"Fork,omitempty"`
	Private              bool     `protobuf:"varint,12,opt,name=Private,proto3" json:"Private,omitempty"`
	Archived             bool     `protobuf:"varint,13,opt,name=Archived,proto3" json:"Archived,omitempty"`
	ForksCount           int64    `protobuf:"varint,14,opt,name=ForksCount,proto3" json:"ForksCount,omitempty"`
	NetworkCount         int64    `protobuf:"varint,15,opt,name=NetworkCount,proto3" json:"NetworkCount,omitempty"`
	OpenIssuesCount      int64    `protobuf:"varint,16,opt,name=OpenIssuesCount,proto3" json:"OpenIssuesCount,omitempty"`
	StargazersCount      int64    `protobuf:"varint,17,opt,name=StargazersCount,proto3" json:"StargazersCount,omitempty"`
	SubscribersCount     int64    `protobuf:"varint,18,opt,name=SubscribersCount,proto3" json:"SubscribersCount,omitempty"`
	WatchersCount        int64    `protobuf:"varint,19,opt,name=WatchersCount,proto3" json:"WatchersCount,omitempty"`
	Size                 int64    `protobuf:"varint,20,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepositoryResponse2) Reset()         { *m = RepositoryResponse2{} }
func (m *RepositoryResponse2) String() string { return proto.CompactTextString(m) }
func (*RepositoryResponse2) ProtoMessage()    {}
func (*RepositoryResponse2) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{8}
}
func (m *RepositoryResponse2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepositoryResponse2.Unmarshal(m, b)
}
func (m *RepositoryResponse2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepositoryResponse2.Marshal(b, m, deterministic)
}
func (dst *RepositoryResponse2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepositoryResponse2.Merge(dst, src)
}
func (m *RepositoryResponse2) XXX_Size() int {
	return xxx_messageInfo_RepositoryResponse2.Size(m)
}
func (m *RepositoryResponse2) XXX_DiscardUnknown() {
	xxx_messageInfo_RepositoryResponse2.DiscardUnknown(m)
}

var xxx_messageInfo_RepositoryResponse2 proto.InternalMessageInfo

func (m *RepositoryResponse2) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RepositoryResponse2) GetNodeID() string {
	if m != nil {
		return m.NodeID
	}
	return ""
}

func (m *RepositoryResponse2) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RepositoryResponse2) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *RepositoryResponse2) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RepositoryResponse2) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *RepositoryResponse2) GetDefaultBranch() string {
	if m != nil {
		return m.DefaultBranch
	}
	return ""
}

func (m *RepositoryResponse2) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *RepositoryResponse2) GetPushedAt() string {
	if m != nil {
		return m.PushedAt
	}
	return ""
}

func (m *RepositoryResponse2) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *RepositoryResponse2) GetFork() bool {
	if m != nil {
		return m.Fork
	}
	return false
}

func (m *RepositoryResponse2) GetPrivate() bool {
	if m != nil {
		return m.Private
	}
	return false
}

func (m *RepositoryResponse2) GetArchived() bool {
	if m != nil {
		return m.Archived
	}
	return false
}

func (m *RepositoryResponse2) GetForksCount() int64 {
	if m != nil {
		return m.ForksCount
	}
	return 0
}

func (m *RepositoryResponse2) GetNetworkCount() int64 {
	if m != nil {
		return m.NetworkCount
	}
	return 0
}

func (m *RepositoryResponse2) GetOpenIssuesCount() int64 {
	if m != nil {
		return m.OpenIssuesCount
	}
	return 0
}

func (m *RepositoryResponse2) GetStargazersCount() int64 {
	if m != nil {
		return m.StargazersCount
	}
	return 0
}

func (m *RepositoryResponse2) GetSubscribersCount() int64 {
	if m != nil {
		return m.SubscribersCount
	}
	return 0
}

func (m *RepositoryResponse2) GetWatchersCount() int64 {
	if m != nil {
		return m.WatchersCount
	}
	return 0
}

func (m *RepositoryResponse2) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ListRepositoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRepositoriesRequest) Reset()         { *m = ListRepositoriesRequest{} }
func (m *ListRepositoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListRepositoriesRequest) ProtoMessage()    {}
func (*ListRepositoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{9}
}
func (m *ListRepositoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRepositoriesRequest.Unmarshal(m, b)
}
func (m *ListRepositoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRepositoriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListRepositoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRepositoriesRequest.Merge(dst, src)
}
func (m *ListRepositoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListRepositoriesRequest.Size(m)
}
func (m *ListRepositoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRepositoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRepositoriesRequest proto.InternalMessageInfo

type ListRepositoriesResponse struct {
	Repositories         []*RepositoryResponse2 `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListRepositoriesResponse) Reset()         { *m = ListRepositoriesResponse{} }
func (m *ListRepositoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListRepositoriesResponse) ProtoMessage()    {}
func (*ListRepositoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dice_105626ff392eab24, []int{10}
}
func (m *ListRepositoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRepositoriesResponse.Unmarshal(m, b)
}
func (m *ListRepositoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRepositoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListRepositoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRepositoriesResponse.Merge(dst, src)
}
func (m *ListRepositoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListRepositoriesResponse.Size(m)
}
func (m *ListRepositoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRepositoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRepositoriesResponse proto.InternalMessageInfo

func (m *ListRepositoriesResponse) GetRepositories() []*RepositoryResponse2 {
	if m != nil {
		return m.Repositories
	}
	return nil
}

func init() {
	proto.RegisterType((*ListUsersRequest)(nil), "protobuf.ListUsersRequest")
	proto.RegisterType((*UserRequest)(nil), "protobuf.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "protobuf.UserResponse")
	proto.RegisterType((*ListUsersResponse)(nil), "protobuf.ListUsersResponse")
	proto.RegisterType((*ActivityResponse)(nil), "protobuf.ActivityResponse")
	proto.RegisterType((*UserActivityResponse)(nil), "protobuf.UserActivityResponse")
	proto.RegisterType((*RepositoryResponse)(nil), "protobuf.RepositoryResponse")
	proto.RegisterType((*UserRepositoriesResponse)(nil), "protobuf.UserRepositoriesResponse")
	proto.RegisterType((*RepositoryResponse2)(nil), "protobuf.RepositoryResponse2")
	proto.RegisterType((*ListRepositoriesRequest)(nil), "protobuf.ListRepositoriesRequest")
	proto.RegisterType((*ListRepositoriesResponse)(nil), "protobuf.ListRepositoriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiceClient is the client API for Dice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UserActivity(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserActivityResponse, error)
	UserRepositories(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserRepositoriesResponse, error)
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
}

type diceClient struct {
	cc *grpc.ClientConn
}

func NewDiceClient(cc *grpc.ClientConn) DiceClient {
	return &diceClient{cc}
}

func (c *diceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceClient) UserActivity(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserActivityResponse, error) {
	out := new(UserActivityResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/UserActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceClient) UserRepositories(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserRepositoriesResponse, error) {
	out := new(UserRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/UserRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Dice/ListRepositories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiceServer is the server API for Dice service.
type DiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UserActivity(context.Context, *UserRequest) (*UserActivityResponse, error)
	UserRepositories(context.Context, *UserRequest) (*UserRepositoriesResponse, error)
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
}

func RegisterDiceServer(s *grpc.Server, srv DiceServer) {
	s.RegisterService(&_Dice_serviceDesc, srv)
}

func _Dice_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dice_UserActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).UserActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/UserActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).UserActivity(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dice_UserRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).UserRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/UserRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).UserRepositories(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dice_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Dice/ListRepositories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Dice",
	HandlerType: (*DiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _Dice_ListUsers_Handler,
		},
		{
			MethodName: "UserActivity",
			Handler:    _Dice_UserActivity_Handler,
		},
		{
			MethodName: "UserRepositories",
			Handler:    _Dice_UserRepositories_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _Dice_ListRepositories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dice.proto",
}

func init() { proto.RegisterFile("dice.proto", fileDescriptor_dice_105626ff392eab24) }

var fileDescriptor_dice_105626ff392eab24 = []byte{
	// 822 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0xdd, 0x8e, 0xda, 0x46,
	0x14, 0x16, 0x3f, 0x4b, 0xe0, 0xc0, 0xee, 0x92, 0xc9, 0x26, 0x99, 0x10, 0x36, 0x25, 0xa3, 0x5e,
	0xd0, 0xaa, 0x5a, 0x24, 0x2a, 0x55, 0xaa, 0xd4, 0x1b, 0x1a, 0x14, 0x09, 0x29, 0xa5, 0x91, 0xb7,
	0xab, 0xf6, 0xa6, 0x42, 0x83, 0x99, 0xc0, 0x28, 0xc6, 0x76, 0x67, 0xc6, 0x54, 0xa4, 0xea, 0x4d,
	0x5e, 0xa1, 0x77, 0x7d, 0x83, 0x3e, 0x4f, 0x5f, 0xa1, 0x2f, 0xd0, 0x37, 0x88, 0xe6, 0xc7, 0xc6,
	0x36, 0xbb, 0x7b, 0xc5, 0x9c, 0xef, 0x7c, 0xe7, 0xff, 0xf8, 0x00, 0xb0, 0xe2, 0x3e, 0xbb, 0x8a,
	0x45, 0xa4, 0x22, 0xd4, 0x34, 0x3f, 0xcb, 0xe4, 0x5d, 0xaf, 0xbf, 0x8e, 0xa2, 0x75, 0xc0, 0x46,
	0x34, 0xe6, 0x23, 0x1a, 0x86, 0x91, 0xa2, 0x8a, 0x47, 0xa1, 0xb4, 0x3c, 0x82, 0xa0, 0xfb, 0x86,
	0x4b, 0x75, 0x23, 0x99, 0x90, 0x1e, 0xfb, 0x2d, 0x61, 0x52, 0x91, 0x2f, 0xa0, 0xad, 0x65, 0x27,
	0xa2, 0x1e, 0x34, 0x13, 0xc9, 0x44, 0x48, 0xb7, 0x0c, 0x57, 0x06, 0x95, 0x61, 0xcb, 0xcb, 0x64,
	0xf2, 0xb1, 0x02, 0x1d, 0xcb, 0x95, 0x71, 0x14, 0x4a, 0x76, 0x1f, 0x19, 0xbd, 0x84, 0xce, 0x8a,
	0xcb, 0x38, 0xa0, 0xfb, 0x85, 0xd1, 0x57, 0x8d, 0xbe, 0xed, 0xb0, 0xb9, 0xa6, 0x5c, 0xc0, 0x09,
	0xdb, 0x52, 0x1e, 0xe0, 0x9a, 0xd1, 0x59, 0x01, 0x5d, 0x02, 0xd0, 0x1d, 0x55, 0x54, 0x2c, 0x12,
	0x11, 0xe0, 0xba, 0x51, 0xb5, 0x2c, 0x72, 0x23, 0x02, 0x32, 0x81, 0x87, 0xb9, 0x1a, 0x5c, 0x22,
	0x5f, 0xc1, 0x89, 0x0e, 0x2c, 0x71, 0x65, 0x50, 0x1b, 0xb6, 0xc7, 0x4f, 0xae, 0xd2, 0x86, 0x5c,
	0xe5, 0xf3, 0xf5, 0x2c, 0x89, 0xfc, 0x5d, 0x81, 0xee, 0xc4, 0x57, 0x7c, 0xc7, 0xd5, 0x3e, 0x73,
	0x71, 0x09, 0xe0, 0x0b, 0x46, 0x15, 0x5b, 0x2d, 0xa8, 0x72, 0xd5, 0xb4, 0x1c, 0x32, 0x51, 0x3a,
	0x57, 0xea, 0xab, 0x48, 0xb8, 0x3a, 0xac, 0x80, 0x9e, 0x43, 0x4b, 0xb0, 0x38, 0xb2, 0x15, 0xda,
	0x2a, 0x9a, 0x1a, 0x30, 0xe5, 0x21, 0xa8, 0xab, 0x7d, 0xcc, 0x5c, 0x09, 0xe6, 0x8d, 0x06, 0xd0,
	0x96, 0xc9, 0x76, 0x4b, 0xc5, 0x3e, 0xe0, 0x21, 0xc3, 0x27, 0xb6, 0x29, 0x39, 0x88, 0xcc, 0xe1,
	0x42, 0xe7, 0x7c, 0x94, 0xdf, 0x37, 0xd0, 0xa4, 0x0e, 0x73, 0x55, 0xf6, 0x0e, 0x55, 0x96, 0xd9,
	0x5e, 0xc6, 0x25, 0x3e, 0x20, 0x8f, 0xc5, 0x91, 0xe4, 0x2a, 0x12, 0x07, 0x6f, 0x08, 0xea, 0xb9,
	0xa9, 0x99, 0x37, 0xfa, 0x16, 0x3a, 0x8a, 0xd1, 0xed, 0x62, 0xcb, 0xb6, 0x4b, 0xdd, 0xcb, 0xea,
	0xbd, 0xbd, 0x6c, 0x6b, 0xee, 0x0f, 0x96, 0x4a, 0x7e, 0x01, 0x6c, 0x95, 0x2e, 0x10, 0x67, 0x87,
	0xd9, 0x7c, 0x07, 0x20, 0xb2, 0x04, 0x5c, 0xea, 0xfd, 0x83, 0xd3, 0xe3, 0xe4, 0xbc, 0x1c, 0x9f,
	0xfc, 0x5f, 0x87, 0x47, 0xc7, 0x94, 0x31, 0x3a, 0x83, 0xea, 0x6c, 0x6a, 0xd2, 0xaf, 0x79, 0xd5,
	0xd9, 0x14, 0x3d, 0x81, 0xc6, 0x3c, 0x5a, 0xb1, 0xd9, 0xd4, 0x0d, 0xc8, 0x49, 0xba, 0xd0, 0xf9,
	0x61, 0x38, 0xe6, 0xad, 0xd7, 0xf6, 0x75, 0x12, 0x04, 0x06, 0xb7, 0xc3, 0xc9, 0x64, 0x3d, 0xa0,
	0x29, 0x93, 0xbe, 0xe0, 0xb1, 0xfe, 0x70, 0xd2, 0x01, 0xe5, 0x20, 0x6d, 0xfd, 0x86, 0x86, 0xeb,
	0x84, 0xae, 0x19, 0x6e, 0x58, 0xeb, 0x54, 0x46, 0x9f, 0xc3, 0xe9, 0x94, 0xbd, 0xa3, 0x49, 0xa0,
	0xbe, 0x17, 0x34, 0xf4, 0x37, 0xf8, 0x81, 0x21, 0x14, 0x41, 0xd4, 0x87, 0xd6, 0xab, 0x74, 0xb1,
	0x70, 0xd3, 0x6e, 0x5a, 0x06, 0x68, 0xff, 0x6f, 0x13, 0xb9, 0x31, 0xca, 0x96, 0xf5, 0x9f, 0xca,
	0xda, 0xf2, 0x26, 0x5e, 0x39, 0x4b, 0xb0, 0x96, 0x19, 0xa0, 0x6b, 0x7d, 0x1d, 0x89, 0xf7, 0xb8,
	0x3d, 0xa8, 0x0c, 0x9b, 0x9e, 0x79, 0x23, 0x0c, 0x0f, 0xde, 0x0a, 0xbe, 0xa3, 0x8a, 0xe1, 0x8e,
	0x81, 0x53, 0x51, 0xc7, 0x99, 0x08, 0x7f, 0xc3, 0x77, 0x6c, 0x85, 0x4f, 0x8d, 0x2a, 0x93, 0xd1,
	0x0b, 0x00, 0x6d, 0x2d, 0x5f, 0x45, 0x49, 0xa8, 0xf0, 0x99, 0xe9, 0x72, 0x0e, 0x41, 0x04, 0x3a,
	0x73, 0xa6, 0x7e, 0x8f, 0xc4, 0x7b, 0xcb, 0x38, 0x37, 0x8c, 0x02, 0x86, 0x86, 0x70, 0xfe, 0x63,
	0xcc, 0xc2, 0x99, 0x94, 0x09, 0x73, 0x8e, 0xba, 0x86, 0x56, 0x86, 0x35, 0xf3, 0x5a, 0x51, 0xb1,
	0xa6, 0x1f, 0x98, 0x70, 0xcc, 0x87, 0x96, 0x59, 0x82, 0xd1, 0x97, 0xd0, 0xbd, 0x4e, 0x96, 0x7a,
	0x16, 0xcb, 0x8c, 0x8a, 0x0c, 0xf5, 0x08, 0xd7, 0xb3, 0xf8, 0x99, 0x2a, 0x7f, 0x93, 0x11, 0x1f,
	0x19, 0x62, 0x11, 0xd4, 0x3d, 0xbb, 0xe6, 0x1f, 0x18, 0xbe, 0x30, 0x4a, 0xf3, 0x26, 0xcf, 0xe0,
	0xa9, 0x3e, 0x31, 0xc5, 0x6d, 0xb6, 0xd7, 0xf2, 0x57, 0xc0, 0xc7, 0x2a, 0xb7, 0xe8, 0x13, 0xe8,
	0x88, 0x1c, 0xee, 0x56, 0xfd, 0xf2, 0xbe, 0x55, 0x1f, 0x7b, 0x05, 0x93, 0xf1, 0x3f, 0x35, 0xa8,
	0x4f, 0xb9, 0xcf, 0xd0, 0x4f, 0xd0, 0xca, 0xae, 0x1c, 0xca, 0x7d, 0xe8, 0xe5, 0xf3, 0xdd, 0x7b,
	0x7e, 0xab, 0xce, 0x7a, 0x27, 0x67, 0x1f, 0xff, 0xfd, 0xef, 0xaf, 0x6a, 0x13, 0x35, 0x46, 0xe6,
	0xf0, 0x21, 0x6e, 0xef, 0x77, 0x7a, 0x2d, 0xd0, 0xe3, 0xf2, 0xb7, 0x6d, 0x7d, 0xbe, 0x28, 0xc2,
	0xe5, 0xe3, 0x42, 0x88, 0x71, 0xdb, 0x47, 0x3d, 0xeb, 0x76, 0xf4, 0x47, 0x7a, 0xf4, 0xff, 0x1c,
	0xa5, 0x67, 0x07, 0x85, 0xd0, 0x2d, 0x5f, 0x84, 0xbb, 0xc2, 0x91, 0x32, 0x7c, 0xdc, 0x5b, 0xf2,
	0x99, 0x09, 0xf9, 0x0c, 0x3d, 0x3d, 0x0e, 0x69, 0x1a, 0x88, 0x62, 0xfb, 0xd7, 0x56, 0x88, 0xf7,
	0xb2, 0xd8, 0x9b, 0x5b, 0xe6, 0x99, 0x8f, 0x7d, 0xd7, 0x5c, 0xc9, 0x63, 0x13, 0xfb, 0x1c, 0x9d,
	0x8e, 0xf2, 0xb3, 0x5a, 0x36, 0x8c, 0xe5, 0xd7, 0x9f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x80,
	0x3b, 0xf3, 0x89, 0x07, 0x00, 0x00,
}
